apiVersion: v1
kind: Pod
metadata:
  name: support-tier
  labels:
    app: microservices
    tier: support
spec:
  containers:
    - name: counter
      image: lrakai/microservices:counter-v1
      env:
        - name: API_URL
          value: http://app-tier.service-discovery:8080

    - name: poller
      image: lrakai/microservices:poller-v1
      env:
        - name: API_URL
          value: http://app-tier.service-discovery:8080
